# Generated by Django 4.2.2 on 2023-06-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_alter_autor_options_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
